import { readdir, readFile, rename, rm, writeFile } from "node:fs/promises";
import path from "node:path";

import { loadConfig } from "../config/loader.js";
import type { PlanningLocalFilesProviderConfig } from "../config/types.js";
import {
  WORK_ITEM_STATUSES,
  WORK_PHASES,
  WORK_PHASES_OR_NONE,
  type WorkItemRecord,
  type WorkItemStatus,
  type WorkPhase,
  type WorkPhaseOrNone,
} from "../domain-model.js";
import { LocalFilesPlanningBackend } from "../providers/planning/local-files-backend.js";

type WriteFn = (message: string) => void;

type LocalCommandFormat = "text" | "json";

export type LocalCommandDependencies = {
  cwd?: () => string;
  stdout?: WriteFn;
  loadConfig?: typeof loadConfig;
  now?: () => string;
};

type SharedLocalCommandOptions = {
  configPath?: string;
  profile?: string;
  format: LocalCommandFormat;
};

type AddIssueCommandOptions = SharedLocalCommandOptions & {
  id?: string;
  identifier?: string;
  title: string;
  description?: string;
  status: WorkItemStatus;
  phase?: WorkPhaseOrNone;
  priority?: number;
  labels: string[];
  parentId?: string;
  dependencyIds: string[];
  blockedByIds: string[];
  blocksIds: string[];
};

type LocalAddIssueResult = {
  planningRoot: string;
  issuePath: string;
  record: WorkItemRecord;
};

type LocalPlanningIndexEntry = {
  id: string;
  identifier: string | null;
  title: string;
  status: WorkItemStatus;
  phase: WorkPhaseOrNone;
  priority: number | null;
  updatedAt: string;
  dependencyIds: string[];
  blockedByIds: string[];
  orchestration: {
    state: WorkItemRecord["orchestration"]["state"];
    owner: string | null;
    runId: string | null;
    leaseUntil: string | null;
  };
};

type LocalPlanningIndex = {
  version: 1;
  updatedAt: string;
  items: LocalPlanningIndexEntry[];
};

const INDEX_VERSION = 1;
const EMPTY_INDEX_UPDATED_AT = "1970-01-01T00:00:00.000Z";
const JSON_FILE_SUFFIX = ".json";

export class LocalCommandError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "LocalCommandError";
  }
}

export async function runLocalCommand(
  args: string[],
  dependencies: LocalCommandDependencies = {},
): Promise<number> {
  if (args.length === 0 || isHelpFlag(args[0])) {
    write(dependencies.stdout, renderLocalHelp());
    return 0;
  }

  const command = args[0];

  if (command === "add-issue") {
    const options = parseAddIssueOptions(args.slice(1));

    if (options === "help") {
      write(dependencies.stdout, renderAddIssueHelp());
      return 0;
    }

    const result = await runAddIssueCommand(options, dependencies);
    const output =
      options.format === "json"
        ? JSON.stringify(
            {
              planningRoot: result.planningRoot,
              issuePath: result.issuePath,
              issue: result.record,
            },
            null,
            2,
          )
        : renderAddIssueResult(result);
    write(dependencies.stdout, output);
    return 0;
  }

  throw new LocalCommandError(`Unknown local command '${command}'.`);
}

export function renderLocalHelp(): string {
  return [
    "Local commands:",
    "  local add-issue            Create a work item in the active planning.local_files store.",
  ].join("\n");
}

function renderAddIssueHelp(): string {
  return [
    "Local add-issue options:",
    "  --config <path>        Config file path. Defaults to ./config.toml.",
    "  --profile <name>       Override the active profile for this command.",
    "  --format <value>       text or json. Defaults to text.",
    "  --id <value>           Override the autogenerated LOCAL-### id.",
    "  --identifier <value>   Override the external identifier. Defaults to the id.",
    "  --title <value>        Required title for the new issue.",
    "  --description <value>  Optional long-form description.",
    `  --status <value>       ${WORK_ITEM_STATUSES.join(", ")}. Defaults to backlog.`,
    "  --phase <value>        Override the phase. Required for blocked issues.",
    "  --priority <n>         Optional non-negative integer priority.",
    "  --label <value>        Repeatable label.",
    "  --parent-id <id>       Optional parent issue id.",
    "  --depends-on <id>      Repeatable dependency id.",
    "  --blocked-by <id>      Repeatable blocker id.",
    "  --blocks <id>          Repeatable downstream issue id.",
  ].join("\n");
}

async function runAddIssueCommand(
  options: AddIssueCommandOptions,
  dependencies: LocalCommandDependencies,
): Promise<LocalAddIssueResult> {
  const cwd = resolveCommandCwd(dependencies.cwd);
  const loadedConfig = await (dependencies.loadConfig ?? loadConfig)({
    cwd,
    configPath: options.configPath,
    activeProfile: options.profile,
    env: process.env,
  });
  const planningProvider = loadedConfig.activeProfile.planningProvider;

  if (planningProvider.kind !== "planning.local_files") {
    throw new LocalCommandError(
      `Profile '${loadedConfig.activeProfileName}' uses '${planningProvider.kind}', but 'local add-issue' requires planning.local_files.`,
    );
  }

  const backend = new LocalFilesPlanningBackend(planningProvider);
  await backend.validateConfig();

  return createLocalIssue({
    planningProvider,
    options,
    now: dependencies.now ?? (() => new Date().toISOString()),
    validate: async () => backend.validateConfig(),
  });
}

async function createLocalIssue(input: {
  planningProvider: PlanningLocalFilesProviderConfig;
  options: AddIssueCommandOptions;
  now: () => string;
  validate: () => Promise<void>;
}): Promise<LocalAddIssueResult> {
  const planningRoot = input.planningProvider.root;
  const issueDirPath = path.join(planningRoot, "issues");
  const indexPath = path.join(planningRoot, "index.json");
  const existingRecords = await readIssueRecords(issueDirPath);
  const existingIds = new Set(existingRecords.map((record) => record.id));
  const nextId = input.options.id ?? generateNextLocalIssueId(existingIds);

  assertSafeWorkItemId(nextId, "id");

  if (existingIds.has(nextId)) {
    throw new LocalCommandError(
      `Work item '${nextId}' already exists under '${issueDirPath}'.`,
    );
  }

  const identifier = input.options.identifier ?? nextId;
  assertNonEmptyString(identifier, "identifier");

  const duplicateIdentifier = existingRecords.find(
    (record) => (record.identifier ?? null) === identifier,
  );

  if (duplicateIdentifier) {
    throw new LocalCommandError(
      `Identifier '${identifier}' is already used by '${duplicateIdentifier.id}'.`,
    );
  }

  const phase = derivePhaseForNewIssue(input.options.status, input.options.phase);
  const timestamp = input.now();
  const record = createWorkItemRecord({
    id: nextId,
    identifier,
    options: input.options,
    timestamp,
    phase,
  });

  assertNoSelfReferences(record);
  assertBlockedByReferences(record, existingIds);

  const issuePath = path.join(issueDirPath, `${record.id}${JSON_FILE_SUFFIX}`);
  const previousIndexSource = await readFile(indexPath, "utf8");
  const index = createIndex([...existingRecords, record]);

  try {
    await writeJsonAtomic(issuePath, record);
    await writeJsonAtomic(indexPath, index);
    await input.validate();
  } catch (error) {
    await rollbackCreateIssue(issuePath, indexPath, previousIndexSource);
    throw error;
  }

  return {
    planningRoot,
    issuePath,
    record,
  };
}

function parseAddIssueOptions(args: string[]): AddIssueCommandOptions | "help" {
  const options: Omit<AddIssueCommandOptions, "title"> & {
    title?: string;
  } = {
    format: "text",
    status: "backlog",
    labels: [],
    dependencyIds: [],
    blockedByIds: [],
    blocksIds: [],
  };

  for (let index = 0; index < args.length; index += 1) {
    const argument = args[index];

    if (isHelpFlag(argument)) {
      return "help";
    }

    switch (argument) {
      case "--config":
        options.configPath = readOptionValue(args, index, argument);
        index += 1;
        break;
      case "--profile":
        options.profile = readOptionValue(args, index, argument);
        index += 1;
        break;
      case "--format":
        options.format = parseFormat(readOptionValue(args, index, argument), argument);
        index += 1;
        break;
      case "--id":
        options.id = readOptionValue(args, index, argument);
        index += 1;
        break;
      case "--identifier":
        options.identifier = readOptionValue(args, index, argument);
        index += 1;
        break;
      case "--title":
        options.title = readOptionValue(args, index, argument);
        index += 1;
        break;
      case "--description":
        options.description = readOptionValue(args, index, argument);
        index += 1;
        break;
      case "--status":
        options.status = parseValue(
          readOptionValue(args, index, argument),
          WORK_ITEM_STATUSES,
          argument,
        );
        index += 1;
        break;
      case "--phase":
        options.phase = parseValue(
          readOptionValue(args, index, argument),
          WORK_PHASES_OR_NONE,
          argument,
        );
        index += 1;
        break;
      case "--priority":
        options.priority = parseNonNegativeInteger(
          readOptionValue(args, index, argument),
          argument,
        );
        index += 1;
        break;
      case "--label":
        options.labels.push(readOptionValue(args, index, argument));
        index += 1;
        break;
      case "--parent-id":
        options.parentId = readOptionValue(args, index, argument);
        index += 1;
        break;
      case "--depends-on":
        options.dependencyIds.push(readOptionValue(args, index, argument));
        index += 1;
        break;
      case "--blocked-by":
        options.blockedByIds.push(readOptionValue(args, index, argument));
        index += 1;
        break;
      case "--blocks":
        options.blocksIds.push(readOptionValue(args, index, argument));
        index += 1;
        break;
      default:
        throw new LocalCommandError(`Unknown local add-issue option '${argument}'.`);
    }
  }

  if (options.title === undefined) {
    throw new LocalCommandError("Local add-issue requires --title.");
  }

  assertNonEmptyString(options.title, "title");

  return {
    ...options,
    title: options.title,
  };
}

function createWorkItemRecord(input: {
  id: string;
  identifier: string;
  options: AddIssueCommandOptions;
  timestamp: string;
  phase: WorkPhaseOrNone;
}): WorkItemRecord {
  const status = input.options.status;

  return {
    id: input.id,
    identifier: input.identifier,
    title: input.options.title.trim(),
    description: input.options.description?.trim() || null,
    status,
    phase: input.phase,
    priority: input.options.priority ?? null,
    labels: uniqueStrings(input.options.labels),
    url: null,
    parentId: input.options.parentId ?? null,
    dependencyIds: uniqueStrings(input.options.dependencyIds),
    blockedByIds: uniqueStrings(input.options.blockedByIds),
    blocksIds: uniqueStrings(input.options.blocksIds),
    artifactUrl: null,
    updatedAt: input.timestamp,
    createdAt: input.timestamp,
    orchestration: {
      state: defaultOrchestrationState(status),
      owner: null,
      runId: null,
      leaseUntil: null,
      reviewOutcome: "none",
      blockedReason: null,
      lastError: null,
      attemptCount: 0,
    },
  };
}

async function readIssueRecords(issueDirPath: string): Promise<WorkItemRecord[]> {
  const entries = await readdir(issueDirPath, {
    withFileTypes: true,
  });
  const records: WorkItemRecord[] = [];

  for (const entry of entries) {
    if (!entry.isFile() || !entry.name.endsWith(JSON_FILE_SUFFIX)) {
      continue;
    }

    const filePath = path.join(issueDirPath, entry.name);
    const raw = JSON.parse(await readFile(filePath, "utf8")) as WorkItemRecord;
    records.push(raw);
  }

  return records;
}

function createIndex(records: WorkItemRecord[]): LocalPlanningIndex {
  const items = records.map(createIndexEntry).sort(compareIndexEntries);
  const updatedAt =
    items.reduce<string | null>((latest, item) => {
      if (latest === null) {
        return item.updatedAt;
      }

      return Date.parse(item.updatedAt) > Date.parse(latest)
        ? item.updatedAt
        : latest;
    }, null) ?? EMPTY_INDEX_UPDATED_AT;

  return {
    version: INDEX_VERSION,
    updatedAt,
    items,
  };
}

function createIndexEntry(record: WorkItemRecord): LocalPlanningIndexEntry {
  return {
    id: record.id,
    identifier: record.identifier ?? null,
    title: record.title,
    status: record.status,
    phase: record.phase,
    priority: record.priority ?? null,
    updatedAt: record.updatedAt,
    dependencyIds: [...record.dependencyIds],
    blockedByIds: [...record.blockedByIds],
    orchestration: {
      state: record.orchestration.state,
      owner: record.orchestration.owner ?? null,
      runId: record.orchestration.runId ?? null,
      leaseUntil: record.orchestration.leaseUntil ?? null,
    },
  };
}

function compareIndexEntries(
  left: LocalPlanningIndexEntry,
  right: LocalPlanningIndexEntry,
): number {
  const leftPriority = left.priority ?? Number.MAX_SAFE_INTEGER;
  const rightPriority = right.priority ?? Number.MAX_SAFE_INTEGER;

  if (leftPriority !== rightPriority) {
    return leftPriority - rightPriority;
  }

  const updatedAtComparison =
    Date.parse(left.updatedAt) - Date.parse(right.updatedAt);

  if (updatedAtComparison !== 0) {
    return updatedAtComparison;
  }

  return left.id.localeCompare(right.id);
}

function generateNextLocalIssueId(existingIds: Set<string>): string {
  let maxValue = 0;
  let maxWidth = 3;

  for (const id of existingIds) {
    const match = /^LOCAL-(\d+)$/.exec(id);

    if (!match) {
      continue;
    }

    maxValue = Math.max(maxValue, Number.parseInt(match[1], 10));
    maxWidth = Math.max(maxWidth, match[1].length);
  }

  return `LOCAL-${String(maxValue + 1).padStart(maxWidth, "0")}`;
}

function derivePhaseForNewIssue(
  status: WorkItemStatus,
  requestedPhase: WorkPhaseOrNone | undefined,
): WorkPhaseOrNone {
  if (status === "blocked") {
    if (requestedPhase === undefined) {
      throw new LocalCommandError(
        "Blocked issues require --phase with one of: design, plan, implement, review, merge.",
      );
    }

    if (requestedPhase === "none") {
      throw new LocalCommandError("Blocked issues cannot use phase 'none'.");
    }

    return requestedPhase;
  }

  const derivedPhase =
    status === "backlog" || status === "done" || status === "canceled"
      ? "none"
      : status;

  if (requestedPhase !== undefined && requestedPhase !== derivedPhase) {
    throw new LocalCommandError(
      `Status '${status}' must use phase '${derivedPhase}', not '${requestedPhase}'.`,
    );
  }

  return derivedPhase;
}

function defaultOrchestrationState(
  status: WorkItemStatus,
): WorkItemRecord["orchestration"]["state"] {
  if (
    status === "design" ||
    status === "plan" ||
    status === "implement" ||
    status === "review"
  ) {
    return "queued";
  }

  if (status === "done") {
    return "completed";
  }

  return "idle";
}

function assertBlockedByReferences(
  record: WorkItemRecord,
  existingIds: Set<string>,
): void {
  for (const blockerId of record.blockedByIds) {
    if (!existingIds.has(blockerId)) {
      throw new LocalCommandError(
        `Blocked-by reference '${blockerId}' does not exist in '${record.id}'.`,
      );
    }
  }
}

function assertNoSelfReferences(record: WorkItemRecord): void {
  const relationFields: Array<[string, string[]]> = [
    ["dependencyIds", record.dependencyIds],
    ["blockedByIds", record.blockedByIds],
    ["blocksIds", record.blocksIds],
  ];

  for (const [fieldName, ids] of relationFields) {
    if (ids.includes(record.id)) {
      throw new LocalCommandError(
        `Work item '${record.id}' cannot reference itself in '${fieldName}'.`,
      );
    }
  }

  if (record.parentId === record.id) {
    throw new LocalCommandError(
      `Work item '${record.id}' cannot use itself as 'parentId'.`,
    );
  }
}

async function rollbackCreateIssue(
  issuePath: string,
  indexPath: string,
  previousIndexSource: string,
): Promise<void> {
  await rm(issuePath, { force: true });
  await writeFile(indexPath, previousIndexSource, "utf8");
}

function renderAddIssueResult(result: LocalAddIssueResult): string {
  return [
    "Local issue created.",
    `ID: ${result.record.id}`,
    `Identifier: ${result.record.identifier ?? "(none)"}`,
    `Status: ${result.record.status}`,
    `Phase: ${result.record.phase}`,
    `Priority: ${result.record.priority ?? "(none)"}`,
    `File: ${result.issuePath}`,
    `Planning root: ${result.planningRoot}`,
  ].join("\n");
}

function resolveCommandCwd(cwdProvider: (() => string) | undefined): string {
  return path.resolve(cwdProvider?.() ?? process.cwd());
}

function isHelpFlag(argument: string): boolean {
  return argument === "--help" || argument === "-h";
}

function readOptionValue(args: string[], index: number, flag: string): string {
  const value = args[index + 1];

  if (value === undefined || value.startsWith("--")) {
    throw new LocalCommandError(`Option '${flag}' requires a value.`);
  }

  return value;
}

function parseFormat(value: string, flag: string): LocalCommandFormat {
  if (value === "text" || value === "json") {
    return value;
  }

  throw new LocalCommandError(`Option '${flag}' must be one of: text, json.`);
}

function parseNonNegativeInteger(value: string, flag: string): number {
  const parsed = Number.parseInt(value, 10);

  if (!Number.isInteger(parsed) || parsed < 0) {
    throw new LocalCommandError(
      `Option '${flag}' must be a non-negative integer.`,
    );
  }

  return parsed;
}

function parseValue<T extends readonly string[]>(
  value: string,
  allowedValues: T,
  flag: string,
): T[number] {
  if ((allowedValues as readonly string[]).includes(value)) {
    return value as T[number];
  }

  throw new LocalCommandError(
    `Option '${flag}' must be one of: ${allowedValues.join(", ")}.`,
  );
}

function uniqueStrings(values: readonly string[]): string[] {
  const result: string[] = [];
  const seen = new Set<string>();

  for (const value of values) {
    const normalized = value.trim();

    if (normalized === "" || seen.has(normalized)) {
      continue;
    }

    seen.add(normalized);
    result.push(normalized);
  }

  return result;
}

async function writeJsonAtomic(filePath: string, value: unknown): Promise<void> {
  const tempPath = `${filePath}.tmp-${process.pid}-${Date.now()}`;
  await writeFile(tempPath, `${JSON.stringify(value, null, 2)}\n`, "utf8");
  await rename(tempPath, filePath);
}

function assertSafeWorkItemId(value: string, fieldName: string): void {
  assertNonEmptyString(value, fieldName);

  if (value.includes("/") || value.includes("\\") || value.includes("\0")) {
    throw new LocalCommandError(`Invalid ${fieldName} '${value}'.`);
  }
}

function assertNonEmptyString(value: string, fieldName: string): void {
  if (value.trim() === "") {
    throw new LocalCommandError(`'${fieldName}' must not be empty.`);
  }
}

function write(writer: WriteFn | undefined, message: string): void {
  (writer ?? console.log)(message);
} 
